[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION= "10.10.0"


[[redirects]]
  from = "/admin/test"
  conditions = {Role = ["admin"]}
  status = 200
  to = "/admin/test2"
  force = true