backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets

collections:
  - label: "Blog in English"
    name: "english"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: course
    filter: {field: "language", value: "en"}
    editor:
     preview: true
    fields:
      - { lavel: "Language", name: "language", widget: "select", options: ["es", "en", "fr", "de", "be", "pt", "nl"] }
      - { label: "Course", name: "course", widget: "string" }
      - { label: "Course Code", name: "course_code", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Code", name: "pipedrive_product_code", widget: "number" }
      - label: "Test Obj"
        name: "test_obj"
        widget: "object"
        fields: 
          - { label: "Level 1", name: "test_level1_1", widget: "string"}
          - { label: "Level 2", name: "test_level1_2", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}

  - label: "Blog en Español"
    name: "spanish"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: course
    filter: {field: "language", value: "es"}
    editor:
     preview: false
    fields:
      - { lavel: "Lenguaje", name: "language", widget: "select", options: ["es", "en", "fr", "de", "be", "pt", "nl"] }
      - { label: "Course", name: "course", widget: "string" }
      - { label: "Course Code", name: "course_code", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Code", name: "pipedrive_product_code", widget: "number" }
      - label: "Test Obj"
        name: "test_obj"
        widget: "object"
        fields: 
          - { label: "Level 1", name: "test_level1_1", widget: "string"}
          - { label: "Level 2", name: "test_level1_2", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}
        

  - label: "Blog en Français"
    name: "french"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: course
    filter: {field: "language", value: "fr"}
    editor:
     preview: false
    fields:
      - { lavel: "Lenguaje", name: "language", widget: "select", options: ["es", "en", "fr", "de", "be", "pt", "nl"] }
      - { label: "Course", name: "course", widget: "string" }
      - { label: "Course Code", name: "course_code", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Code", name: "pipedrive_product_code", widget: "number" }
      - label: "Test Obj"
        name: "test_obj"
        widget: "object"
        fields: 
          - { label: "Level 1", name: "test_level1_1", widget: "string"}
          - { label: "Level 2", name: "test_level1_2", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}
        

  - label: "Blog auf Deutsch"
    name: "german"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: course
    filter: {field: "language", value: "de"}
    editor:
     preview: false
    fields:
      - { lavel: "Lenguaje", name: "language", widget: "select", options: ["es", "en", "fr", "de", "be", "pt", "nl"] }
      - { label: "Course", name: "course", widget: "string" }
      - { label: "Course Code", name: "course_code", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Code", name: "pipedrive_product_code", widget: "number" }
      - label: "Test Obj"
        name: "test_obj"
        widget: "object"
        fields: 
          - { label: "Level 1", name: "test_level1_1", widget: "string"}
          - { label: "Level 2", name: "test_level1_2", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}
        

  - label: "Blog em Português Brazilian"
    name: "brazilian"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: course
    filter: {field: "language", value: "be"}
    editor:
     preview: false
    fields:
      - { lavel: "Lenguaje", name: "language", widget: "select", options: ["es", "en", "fr", "de", "be", "pt", "nl"] }
      - { label: "Course", name: "course", widget: "string" }
      - { label: "Course Code", name: "course_code", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Code", name: "pipedrive_product_code", widget: "number" }
      - label: "Test Obj"
        name: "test_obj"
        widget: "object"
        fields: 
          - { label: "Level 1", name: "test_level1_1", widget: "string"}
          - { label: "Level 2", name: "test_level1_2", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}
        

  - label: "Blog em Português"
    name: "portuguese"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: course
    filter: {field: "language", value: "pt"}
    editor:
     preview: false
    fields:
      - { lavel: "Language", name: "language", widget: "select", options: ["es", "en", "fr", "de", "be", "pt", "nl"] }
      - { label: "Course", name: "course", widget: "string" }
      - { label: "Course Code", name: "course_code", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Code", name: "pipedrive_product_code", widget: "number" }
      - label: "Test Obj"
        name: "test_obj"
        widget: "object"
        fields: 
          - { label: "Level 1", name: "test_level1_1", widget: "string"}
          - { label: "Level 2", name: "test_level1_2", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}
        

  - label: "Blog in het Nederlands"
    name: "dutch"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: course
    filter: {field: "language", value: "nl"}
    editor:
     preview: false
    fields:
      - { lavel: "Language", name: "language", widget: "select", options: ["es", "en", "fr", "de", "be", "pt", "nl"] }
      - { label: "Course", name: "course", widget: "string" }
      - { label: "Course Code", name: "course_code", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Code", name: "pipedrive_product_code", widget: "number" }
      - label: "Test Obj"
        name: "test_obj"
        widget: "object"
        fields: 
          - { label: "Level 1", name: "test_level1_1", widget: "string"}
          - { label: "Level 2", name: "test_level1_2", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown"}
        
        
  - label: "Prueba organización"
    name: "organizacion"
    create: false
    files:
      - label: "Level1_1"
        name: "level1_1"
        file: "src/pages/blog/level1/level1_1.md"
        fields: 
          - { label: "name", name: "name", widget: "string"}
      - label: "Level1_2"
        name: "level1_2"
        file: "src/pages/blog/level1/level1_2.yml"
        fields:
          - { label: "name2", name: "name2", widget: "string"}

  - label: "Home Español"
    name: "home_español"
    editor:
      preview: true
    files:
      - label: "Footer"
        name: "footer"
        file: "content/Home/Footer.md"
        fields:
          - label: "Nuestros Campus"
            name: "campus"
            widget: "object"
            fields :
              - {label: Name, name: name, widget: string}
