backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: course
    editor:
     preview: false
    fields:
      - { label: "Course", name: "course", widget: "string" }
      - { label: "Course Code", name: "course_code", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Code", name: "pipedrive_product_code", widget: "number" }
      
      -  
          label: Test Obj
          name: test_obj
          widget: list
          fields: 
            - { label: "Level 1", name: "test_level_1_1", widget: "string"}
            - { label: "Level 2", name: "test_level_1_2", widget: "string"}
        
